databaseType = "PostgreSql"
id = "0afa2643-0ba5-410d-a91f-5aef76f09c87"
name = "mz_studios_db"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true
baselineOnMigrate = false

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "dev"

[flywayDesktop.generate]
undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.dev]
schemas = [ "app", "public" ]
displayName = "Development"

[environments.prod]
schemas = [ "app", "public" ]
displayName = "Production"

